{"name": "test_4[35-test.email@mail.com]", "status": "failed", "statusDetails": {"message": "AssertionError: test failed\nassert '35' == 'test.email@mail.com'\n  - test.email@mail.com\n  + 35", "trace": "self = <tests.test_negative.TestNegative object at 0x000001EF078255E0>, email_input = '35', email_output = 'test.email@mail.com'\n\n    @pytest.mark.parametrize(\"email_input, email_output\", [(\"35\", \"test.email@mail.com\"), (\" \", \"test.email@mail.com\"),\n                                                           (\"test.email_mail.com\", \"test.email@mail.com\"),\n                                                           (\"test.email@\", \"test.email@mail.com\")])\n    def test_4(self, email_input, email_output):\n        driver = self.driver\n        contact = ContactUs(driver)\n        contact.input_email(email_input)\n>       assert email_input == email_output, \"test failed\"\nE       AssertionError: test failed\nE       assert '35' == 'test.email@mail.com'\nE         - test.email@mail.com\nE         + 35\n\ntests\\test_negative.py:34: AssertionError"}, "parameters": [{"name": "email_input", "value": "'35'"}, {"name": "email_output", "value": "'test.email@mail.com'"}], "start": 1634717806110, "stop": 1634717806208, "uuid": "2bf6b0fc-3d6e-4190-886d-eab1d925127b", "historyId": "b07e8e82b2825acf5b85a11462469bf8", "testCaseId": "aa2b087f31254c304061bd1a0e37df53", "fullName": "tests.test_negative.TestNegative#test_4", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_negative"}, {"name": "subSuite", "value": "TestNegative"}, {"name": "host", "value": "SIS2W066"}, {"name": "thread", "value": "6828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_negative"}]}